
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;
-- categores テーブル
CREATE TABLE categories
(
id SERIAL PRIMARY KEY,
name VARCHAR(50)
);
-- users テーブルを作成するクエリ
CREATE TABLE users (
id INTEGER  GENERATED BY DEFAULT AS  IDENTITY PRIMARY KEY, 
email  VARCHAR(50),
name VARCHAR(20),
password VARCHAR(255)

);

-- tasks テーブルを作成するクエリ
CREATE TABLE tasks (
id INTEGER GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
category_id INTEGER,
user_id INTEGER,
title VARCHAR(50),
closing_date DATE,
progress INTEGER,
memo TEXT,
FOREIGN KEY(category_id) REFERENCES categories(id),
FOREIGN KEY(user_id) REFERENCES users(id)

);

